/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *label21;
  GtkWidget *image1;
  GtkWidget *hbuttonbox2;
  GtkWidget *button17;
  GtkWidget *label44;
  GtkWidget *hseparator1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("gXNeur About..."));
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  label21 = gtk_label_new (_("\n\t\t<b>X Neural Switcher for Gnome</b>\t\t\n\t\tGTK2 frontend for XNeur\t\t\n\nAUTHORS:\nAndrew Crew Kuznetsov\nNikolay Yankin"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (vbox1), label21, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_CENTER);

  image1 = create_pixmap (window1, "gxneur.png");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (vbox1), image1, TRUE, TRUE, 4);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_end (GTK_BOX (vbox1), hbuttonbox2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox2), 3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);

  button17 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button17);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  label44 = gtk_label_new ("");
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (vbox1), label44, FALSE, FALSE, 3);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, TRUE, TRUE, 0);

  g_signal_connect_swapped ((gpointer) button17, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (window1));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (window1, button17, "button17");
  GLADE_HOOKUP_OBJECT (window1, label44, "label44");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GdkPixbuf *window2_icon_pixbuf;
  GtkWidget *vbox7;
  GtkWidget *notebook1;
  GtkWidget *vbox2;
  GtkWidget *hbox2;
  GtkWidget *label5;
  GtkWidget *combobox1;
  GtkWidget *hseparator2;
  GtkWidget *vbox5;
  GtkWidget *label16;
  GtkWidget *table1;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkWidget *entry14;
  GtkWidget *entry15;
  GtkWidget *entry16;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *entry17;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *entry20;
  GtkWidget *label49;
  GtkWidget *label2;
  GtkWidget *table2;
  GtkWidget *label18;
  GtkWidget *label20;
  GtkWidget *combobox13;
  GtkWidget *combobox14;
  GtkWidget *combobox15;
  GtkWidget *combobox16;
  GtkWidget *button8;
  GtkWidget *button9;
  GtkWidget *button6;
  GtkWidget *button7;
  GtkWidget *combobox21;
  GtkWidget *combobox22;
  GtkWidget *combobox23;
  GtkWidget *combobox24;
  GtkWidget *button23;
  GtkWidget *button24;
  GtkWidget *button25;
  GtkWidget *button26;
  GtkWidget *combobox25;
  GtkWidget *label50;
  GtkWidget *label3;
  GtkWidget *vbox8;
  GtkWidget *vbox3;
  GtkWidget *label6;
  GtkWidget *hbox3;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *vbox4;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *hseparator3;
  GtkWidget *vbox10;
  GtkWidget *label23;
  GtkWidget *hbox4;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview2;
  GtkWidget *vbox11;
  GtkWidget *button19;
  GtkWidget *button20;
  GtkWidget *hseparator4;
  GtkWidget *vbox12;
  GtkWidget *label24;
  GtkWidget *hbox5;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview3;
  GtkWidget *vbox13;
  GtkWidget *button21;
  GtkWidget *button22;
  GtkWidget *label22;
  GtkWidget *vbox14;
  GtkWidget *checkbutton5;
  GtkWidget *hseparator5;
  GtkWidget *table4;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *entry21;
  GtkWidget *entry22;
  GtkWidget *entry23;
  GtkWidget *entry24;
  GtkWidget *entry25;
  GtkWidget *entry26;
  GtkWidget *entry27;
  GtkWidget *entry28;
  GtkWidget *entry29;
  GtkWidget *entry30;
  GtkWidget *entry31;
  GtkWidget *entry32;
  GtkWidget *entry33;
  GtkWidget *entry34;
  GtkWidget *label45;
  GtkWidget *table3;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *label51;
  GtkWidget *hbuttonbox1;
  GtkWidget *button4;
  GtkWidget *button5;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("XNeur Settings"));
  gtk_window_set_resizable (GTK_WINDOW (window2), FALSE);
  window2_icon_pixbuf = create_pixbuf ("gxneur.png");
  if (window2_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window2), window2_icon_pixbuf);
      gdk_pixbuf_unref (window2_icon_pixbuf);
    }

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (window2), vbox7);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox7), notebook1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (notebook1), 3);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), vbox2,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 3);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, FALSE, TRUE, 0);

  label5 = gtk_label_new (_("<b>Processing Mode\t\t</b>"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_box_pack_start (GTK_BOX (hbox2), combobox1, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Automatic"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Manual"));

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator2, FALSE, TRUE, 4);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (vbox2), vbox5, FALSE, TRUE, 0);

  label16 = gtk_label_new (_("<b>Key Bindings</b>"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (vbox5), label16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  table1 = gtk_table_new (10, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox5), table1, FALSE, TRUE, 0);

  label12 = gtk_label_new (_("Replace Selected Text"));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table1), label12, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  label13 = gtk_label_new (_("Change Processing Mode"));
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table1), label13, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  label14 = gtk_label_new (_("Replace Last String "));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table1), label14, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("Replace / Cancel Replace "));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table1), label15, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label26 = gtk_label_new (_("Transliterate Selected Text"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table1), label26, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("Change Case Of Selected Text "));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table1), label27, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_table_attach (GTK_TABLE (table1), entry11, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry11), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 9679);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_table_attach (GTK_TABLE (table1), entry12, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry12), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 9679);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_table_attach (GTK_TABLE (table1), entry13, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry13), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 9679);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_table_attach (GTK_TABLE (table1), entry14, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry14), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 9679);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_table_attach (GTK_TABLE (table1), entry15, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry15), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 9679);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_table_attach (GTK_TABLE (table1), entry16, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry16), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 9679);

  label46 = gtk_label_new (_("Enable First Layout  "));
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table1), label46, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label46), 0, 0.5);

  label47 = gtk_label_new (_("Enable Secondary Layout"));
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table1), label47, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  label48 = gtk_label_new (_("Enable Third Layout"));
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table1), label48, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label48), 0, 0.5);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_table_attach (GTK_TABLE (table1), entry17, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry17), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 9679);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_table_attach (GTK_TABLE (table1), entry18, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry18), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 9679);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_table_attach (GTK_TABLE (table1), entry19, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry19), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 9679);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_table_attach (GTK_TABLE (table1), entry20, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry20), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 9679);

  label49 = gtk_label_new (_("Enable Fourth Layout"));
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table1), label49, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label49), 0, 0.5);

  label2 = gtk_label_new (_("Preferences"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label2);

  table2 = gtk_table_new (6, 4, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 3);

  label18 = gtk_label_new (_("Layout"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table2), label18, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label20 = gtk_label_new (_("Number\t"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table2), label20, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  combobox13 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox13);
  gtk_table_attach (GTK_TABLE (table2), combobox13, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("3"));

  combobox14 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox14);
  gtk_table_attach (GTK_TABLE (table2), combobox14, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox14), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox14), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox14), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox14), _("3"));

  combobox15 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox15);
  gtk_table_attach (GTK_TABLE (table2), combobox15, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox15), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox15), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox15), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox15), _("3"));

  combobox16 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox16);
  gtk_table_attach (GTK_TABLE (table2), combobox16, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox16), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox16), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox16), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox16), _("3"));

  button8 = gtk_button_new_with_mnemonic (_("Dictionary..."));
  gtk_widget_show (button8);
  gtk_table_attach (GTK_TABLE (table2), button8, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button9 = gtk_button_new_with_mnemonic (_("Dictionary..."));
  gtk_widget_show (button9);
  gtk_table_attach (GTK_TABLE (table2), button9, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button6 = gtk_button_new_with_mnemonic (_("Dictionary..."));
  gtk_widget_show (button6);
  gtk_table_attach (GTK_TABLE (table2), button6, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button7 = gtk_button_new_with_mnemonic (_("Dictionary..."));
  gtk_widget_show (button7);
  gtk_table_attach (GTK_TABLE (table2), button7, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combobox21 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox21);
  gtk_table_attach (GTK_TABLE (table2), combobox21, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox21), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox21), _("English"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox21), _("Russian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox21), _("Ukrainian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox21), _("Belarusian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox21), _("French"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox21), _("Romanian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox21), _("Kazakh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox21), _("German"));

  combobox22 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox22);
  gtk_table_attach (GTK_TABLE (table2), combobox22, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox22), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox22), _("English"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox22), _("Russian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox22), _("Ukrainian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox22), _("Belarusian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox22), _("French"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox22), _("Romanian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox22), _("Kazakh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox22), _("German"));

  combobox23 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox23);
  gtk_table_attach (GTK_TABLE (table2), combobox23, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox23), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox23), _("English"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox23), _("Russian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox23), _("Ukrainian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox23), _("Belarusian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox23), _("French"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox23), _("Romanian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox23), _("Kazakh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox23), _("German"));

  combobox24 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox24);
  gtk_table_attach (GTK_TABLE (table2), combobox24, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox24), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox24), _("English"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox24), _("Russian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox24), _("Ukrainian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox24), _("Belarusian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox24), _("French"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox24), _("Romanian"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox24), _("Kazakh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox24), _("German"));

  button23 = gtk_button_new_with_mnemonic (_("Regular Expressions..."));
  gtk_widget_show (button23);
  gtk_table_attach (GTK_TABLE (table2), button23, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button24 = gtk_button_new_with_mnemonic (_("Regular Expressions..."));
  gtk_widget_show (button24);
  gtk_table_attach (GTK_TABLE (table2), button24, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button25 = gtk_button_new_with_mnemonic (_("Regular Expressions..."));
  gtk_widget_show (button25);
  gtk_table_attach (GTK_TABLE (table2), button25, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button26 = gtk_button_new_with_mnemonic (_("Regular Expressions..."));
  gtk_widget_show (button26);
  gtk_table_attach (GTK_TABLE (table2), button26, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combobox25 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox25);
  gtk_table_attach (GTK_TABLE (table2), combobox25, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox25), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox25), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox25), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox25), _("3"));

  label50 = gtk_label_new (_("Initial Layout Number "));
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table2), label50, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label50), 0, 0.5);

  label3 = gtk_label_new (_("Layouts"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label3);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox8);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox3, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("Do not process these applications:"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox3), label6, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (hbox3), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview1), FALSE);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox4, TRUE, TRUE, 0);

  button2 = gtk_button_new_with_mnemonic (_("Add..."));
  gtk_widget_show (button2);
  gtk_box_pack_start (GTK_BOX (vbox4), button2, FALSE, FALSE, 0);

  button3 = gtk_button_new_with_mnemonic (_("Remove"));
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (vbox4), button3, FALSE, FALSE, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox8), hseparator3, TRUE, TRUE, 4);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox10, TRUE, TRUE, 0);

  label23 = gtk_label_new (_("Force Automatic Mode for these applications:"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (vbox10), label23, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  hbox4 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox4, TRUE, TRUE, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (hbox4), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview2);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview2), FALSE);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox11, TRUE, TRUE, 0);

  button19 = gtk_button_new_with_mnemonic (_("Add..."));
  gtk_widget_show (button19);
  gtk_box_pack_start (GTK_BOX (vbox11), button19, FALSE, FALSE, 0);

  button20 = gtk_button_new_with_mnemonic (_("Remove"));
  gtk_widget_show (button20);
  gtk_box_pack_start (GTK_BOX (vbox11), button20, FALSE, FALSE, 0);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox8), hseparator4, TRUE, TRUE, 4);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox12, TRUE, TRUE, 0);

  label24 = gtk_label_new (_("Force Manual Mode for these applications:"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (vbox12), label24, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  hbox5 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox5, TRUE, TRUE, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (hbox5), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview3);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview3), FALSE);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox13, TRUE, TRUE, 0);

  button21 = gtk_button_new_with_mnemonic (_("Add..."));
  gtk_widget_show (button21);
  gtk_box_pack_start (GTK_BOX (vbox13), button21, FALSE, FALSE, 0);

  button22 = gtk_button_new_with_mnemonic (_("Remove"));
  gtk_widget_show (button22);
  gtk_box_pack_start (GTK_BOX (vbox13), button22, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("Applications"));
  gtk_widget_show (label22);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label22);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox14);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox14);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("Play Sounds"));
  gtk_widget_show (checkbutton5);
  gtk_box_pack_start (GTK_BOX (vbox14), checkbutton5, FALSE, FALSE, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (vbox14), hseparator5, FALSE, TRUE, 0);

  table4 = gtk_table_new (14, 2, FALSE);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox14), table4, TRUE, TRUE, 0);

  label52 = gtk_label_new (_("Press Key On Layout 1"));
  gtk_widget_show (label52);
  gtk_table_attach (GTK_TABLE (table4), label52, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label52), 0, 0.5);

  label53 = gtk_label_new (_("Press Key On Layout 2"));
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table4), label53, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);

  label54 = gtk_label_new (_("Press Key On Layout 3"));
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table4), label54, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);

  label55 = gtk_label_new (_("Press Key On Layout 4"));
  gtk_widget_show (label55);
  gtk_table_attach (GTK_TABLE (table4), label55, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label55), 0, 0.5);

  label56 = gtk_label_new (_("Enable Layout 1"));
  gtk_widget_show (label56);
  gtk_table_attach (GTK_TABLE (table4), label56, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label56), 0, 0.5);

  label57 = gtk_label_new (_("Enable Layout 2"));
  gtk_widget_show (label57);
  gtk_table_attach (GTK_TABLE (table4), label57, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label57), 0, 0.5);

  label58 = gtk_label_new (_("Enable Layout 3"));
  gtk_widget_show (label58);
  gtk_table_attach (GTK_TABLE (table4), label58, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label58), 0, 0.5);

  label59 = gtk_label_new (_("Enable Layout 4"));
  gtk_widget_show (label59);
  gtk_table_attach (GTK_TABLE (table4), label59, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label59), 0, 0.5);

  label60 = gtk_label_new (_("Automatic Change Word"));
  gtk_widget_show (label60);
  gtk_table_attach (GTK_TABLE (table4), label60, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label60), 0, 0.5);

  label61 = gtk_label_new (_("Manual Change Word"));
  gtk_widget_show (label61);
  gtk_table_attach (GTK_TABLE (table4), label61, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label61), 0, 0.5);

  label62 = gtk_label_new (_("Change String"));
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table4), label62, 0, 1, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label62), 0, 0.5);

  label63 = gtk_label_new (_("Change Selected Text"));
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table4), label63, 0, 1, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label63), 0, 0.5);

  label64 = gtk_label_new (_("Translit Selected Text"));
  gtk_widget_show (label64);
  gtk_table_attach (GTK_TABLE (table4), label64, 0, 1, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label64), 0, 0.5);

  label65 = gtk_label_new (_("Changecase Selected Text"));
  gtk_widget_show (label65);
  gtk_table_attach (GTK_TABLE (table4), label65, 0, 1, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label65), 0, 0.5);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_table_attach (GTK_TABLE (table4), entry21, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 9679);

  entry22 = gtk_entry_new ();
  gtk_widget_show (entry22);
  gtk_table_attach (GTK_TABLE (table4), entry22, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 9679);

  entry23 = gtk_entry_new ();
  gtk_widget_show (entry23);
  gtk_table_attach (GTK_TABLE (table4), entry23, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry23), 9679);

  entry24 = gtk_entry_new ();
  gtk_widget_show (entry24);
  gtk_table_attach (GTK_TABLE (table4), entry24, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24), 9679);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_table_attach (GTK_TABLE (table4), entry25, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 9679);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_table_attach (GTK_TABLE (table4), entry26, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 9679);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_table_attach (GTK_TABLE (table4), entry27, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 9679);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_table_attach (GTK_TABLE (table4), entry28, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 9679);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_table_attach (GTK_TABLE (table4), entry29, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 9679);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_table_attach (GTK_TABLE (table4), entry30, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 9679);

  entry31 = gtk_entry_new ();
  gtk_widget_show (entry31);
  gtk_table_attach (GTK_TABLE (table4), entry31, 1, 2, 10, 11,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry31), 9679);

  entry32 = gtk_entry_new ();
  gtk_widget_show (entry32);
  gtk_table_attach (GTK_TABLE (table4), entry32, 1, 2, 11, 12,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry32), 9679);

  entry33 = gtk_entry_new ();
  gtk_widget_show (entry33);
  gtk_table_attach (GTK_TABLE (table4), entry33, 1, 2, 12, 13,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry33), 9679);

  entry34 = gtk_entry_new ();
  gtk_widget_show (entry34);
  gtk_table_attach (GTK_TABLE (table4), entry34, 1, 2, 13, 14,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry34), 9679);

  label45 = gtk_label_new (_("Sounds"));
  gtk_widget_show (label45);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label45);

  table3 = gtk_table_new (4, 1, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (notebook1), table3);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Process Mouse Events"));
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table3), checkbutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Enable Auto-Learn Mode"));
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table3), checkbutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("Remember Keyboard Layout For Each Window"));
  gtk_widget_show (checkbutton3);
  gtk_table_attach (GTK_TABLE (table3), checkbutton3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("Keep Selection After Changing Selected Text"));
  gtk_widget_show (checkbutton4);
  gtk_table_attach (GTK_TABLE (table3), checkbutton4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label51 = gtk_label_new (_("Advanced"));
  gtk_widget_show (label51);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label51);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox7), hbuttonbox1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  button4 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button4);
  gtk_container_set_border_width (GTK_CONTAINER (button4), 3);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  button5 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button5);
  gtk_container_set_border_width (GTK_CONTAINER (button5), 3);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) window2, "delete_event",
                            G_CALLBACK (on_window2_delete_event),
                            GTK_OBJECT (window2));
  g_signal_connect_swapped ((gpointer) entry11, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry11));
  g_signal_connect_swapped ((gpointer) entry11, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry11));
  g_signal_connect_swapped ((gpointer) entry12, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry12));
  g_signal_connect_swapped ((gpointer) entry12, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry12));
  g_signal_connect_swapped ((gpointer) entry13, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry13));
  g_signal_connect_swapped ((gpointer) entry13, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry13));
  g_signal_connect_swapped ((gpointer) entry14, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry14));
  g_signal_connect_swapped ((gpointer) entry14, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry14));
  g_signal_connect_swapped ((gpointer) entry15, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry15));
  g_signal_connect_swapped ((gpointer) entry15, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry15));
  g_signal_connect_swapped ((gpointer) entry16, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry16));
  g_signal_connect_swapped ((gpointer) entry16, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry16));
  g_signal_connect_swapped ((gpointer) entry17, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry17));
  g_signal_connect_swapped ((gpointer) entry17, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry17));
  g_signal_connect_swapped ((gpointer) entry18, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry18));
  g_signal_connect_swapped ((gpointer) entry18, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry18));
  g_signal_connect_swapped ((gpointer) entry19, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry19));
  g_signal_connect_swapped ((gpointer) entry19, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry19));
  g_signal_connect_swapped ((gpointer) entry20, "key_press_event",
                            G_CALLBACK (on_key_press_event),
                            GTK_OBJECT (entry20));
  g_signal_connect_swapped ((gpointer) entry20, "key_release_event",
                            G_CALLBACK (on_key_release_event),
                            GTK_OBJECT (entry20));
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (on_button23_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_button24_clicked),
                    NULL);
  g_signal_connect ((gpointer) button25, "clicked",
                    G_CALLBACK (on_button25_clicked),
                    NULL);
  g_signal_connect ((gpointer) button26, "clicked",
                    G_CALLBACK (on_button26_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (window2, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window2, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");
  GLADE_HOOKUP_OBJECT (window2, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window2, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window2, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (window2, label16, "label16");
  GLADE_HOOKUP_OBJECT (window2, table1, "table1");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, label26, "label26");
  GLADE_HOOKUP_OBJECT (window2, label27, "label27");
  GLADE_HOOKUP_OBJECT (window2, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window2, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (window2, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (window2, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (window2, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (window2, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (window2, label46, "label46");
  GLADE_HOOKUP_OBJECT (window2, label47, "label47");
  GLADE_HOOKUP_OBJECT (window2, label48, "label48");
  GLADE_HOOKUP_OBJECT (window2, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (window2, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (window2, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (window2, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (window2, label49, "label49");
  GLADE_HOOKUP_OBJECT (window2, label2, "label2");
  GLADE_HOOKUP_OBJECT (window2, table2, "table2");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, combobox13, "combobox13");
  GLADE_HOOKUP_OBJECT (window2, combobox14, "combobox14");
  GLADE_HOOKUP_OBJECT (window2, combobox15, "combobox15");
  GLADE_HOOKUP_OBJECT (window2, combobox16, "combobox16");
  GLADE_HOOKUP_OBJECT (window2, button8, "button8");
  GLADE_HOOKUP_OBJECT (window2, button9, "button9");
  GLADE_HOOKUP_OBJECT (window2, button6, "button6");
  GLADE_HOOKUP_OBJECT (window2, button7, "button7");
  GLADE_HOOKUP_OBJECT (window2, combobox21, "combobox21");
  GLADE_HOOKUP_OBJECT (window2, combobox22, "combobox22");
  GLADE_HOOKUP_OBJECT (window2, combobox23, "combobox23");
  GLADE_HOOKUP_OBJECT (window2, combobox24, "combobox24");
  GLADE_HOOKUP_OBJECT (window2, button23, "button23");
  GLADE_HOOKUP_OBJECT (window2, button24, "button24");
  GLADE_HOOKUP_OBJECT (window2, button25, "button25");
  GLADE_HOOKUP_OBJECT (window2, button26, "button26");
  GLADE_HOOKUP_OBJECT (window2, combobox25, "combobox25");
  GLADE_HOOKUP_OBJECT (window2, label50, "label50");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");
  GLADE_HOOKUP_OBJECT (window2, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (window2, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");
  GLADE_HOOKUP_OBJECT (window2, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window2, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window2, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (window2, button2, "button2");
  GLADE_HOOKUP_OBJECT (window2, button3, "button3");
  GLADE_HOOKUP_OBJECT (window2, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window2, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (window2, label23, "label23");
  GLADE_HOOKUP_OBJECT (window2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (window2, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window2, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (window2, button19, "button19");
  GLADE_HOOKUP_OBJECT (window2, button20, "button20");
  GLADE_HOOKUP_OBJECT (window2, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (window2, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (window2, label24, "label24");
  GLADE_HOOKUP_OBJECT (window2, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (window2, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window2, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (window2, button21, "button21");
  GLADE_HOOKUP_OBJECT (window2, button22, "button22");
  GLADE_HOOKUP_OBJECT (window2, label22, "label22");
  GLADE_HOOKUP_OBJECT (window2, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (window2, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (window2, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (window2, table4, "table4");
  GLADE_HOOKUP_OBJECT (window2, label52, "label52");
  GLADE_HOOKUP_OBJECT (window2, label53, "label53");
  GLADE_HOOKUP_OBJECT (window2, label54, "label54");
  GLADE_HOOKUP_OBJECT (window2, label55, "label55");
  GLADE_HOOKUP_OBJECT (window2, label56, "label56");
  GLADE_HOOKUP_OBJECT (window2, label57, "label57");
  GLADE_HOOKUP_OBJECT (window2, label58, "label58");
  GLADE_HOOKUP_OBJECT (window2, label59, "label59");
  GLADE_HOOKUP_OBJECT (window2, label60, "label60");
  GLADE_HOOKUP_OBJECT (window2, label61, "label61");
  GLADE_HOOKUP_OBJECT (window2, label62, "label62");
  GLADE_HOOKUP_OBJECT (window2, label63, "label63");
  GLADE_HOOKUP_OBJECT (window2, label64, "label64");
  GLADE_HOOKUP_OBJECT (window2, label65, "label65");
  GLADE_HOOKUP_OBJECT (window2, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (window2, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (window2, entry23, "entry23");
  GLADE_HOOKUP_OBJECT (window2, entry24, "entry24");
  GLADE_HOOKUP_OBJECT (window2, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (window2, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (window2, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (window2, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (window2, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (window2, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (window2, entry31, "entry31");
  GLADE_HOOKUP_OBJECT (window2, entry32, "entry32");
  GLADE_HOOKUP_OBJECT (window2, entry33, "entry33");
  GLADE_HOOKUP_OBJECT (window2, entry34, "entry34");
  GLADE_HOOKUP_OBJECT (window2, label45, "label45");
  GLADE_HOOKUP_OBJECT (window2, table3, "table3");
  GLADE_HOOKUP_OBJECT (window2, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window2, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window2, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window2, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (window2, label51, "label51");
  GLADE_HOOKUP_OBJECT (window2, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window2, button4, "button4");
  GLADE_HOOKUP_OBJECT (window2, button5, "button5");

  return window2;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GdkPixbuf *dialog1_icon_pixbuf;
  GtkWidget *dialog_vbox1;
  GtkWidget *entry10;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview1;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog1), _("File Editing"));
  gtk_window_set_resizable (GTK_WINDOW (dialog1), FALSE);
  dialog1_icon_pixbuf = create_pixbuf ("gxneur.png");
  if (dialog1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog1), dialog1_icon_pixbuf);
      gdk_pixbuf_unref (dialog1_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), entry10, FALSE, FALSE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry10), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 9679);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), scrolledwindow3, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow3, 384, 371);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview1);
  gtk_container_set_border_width (GTK_CONTAINER (textview1), 3);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) cancelbutton1, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dialog1));
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (dialog1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (dialog1, textview1, "textview1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton1, "okbutton1");

  return dialog1;
}

