.TH XNEUR 1 
.SH NAME
XNeur - in-place conversion of text typed in with a wrong keyboard layout
.SH SYNOPSIS
.B "xneur"
[options]
.SH DESCRIPTION
.PP
When users work in multilingual environment (e.g. Russian+English), they sometimes type in text with wrong keyboard layout. In auto mode \fIXNeur\fP can automatically detect language of word user typed, switch keyboard layout and convert word from one keyboard layout into another. In manual mode user has ability to convert last typed word or some selected text with hot-keys. The main idea of this utility is similar to Punto Switcher for MS Windows. For now \fIXNeur\fP support English, Russian, Ukrainian, Belarusian, French, Romanian, Kazakh, German and more in future. 
.SH OPTIONS
.TP 8
.B \-v, \--version 
Print version and exit.
.TP 8
.B \-h, \--help 
Print short help.
.TP 8
.B \-a, \--about
About for \fIXNeur\fP.
.TP 8
.B \-f, \--force 
Skip check for other instances of \fIXNeur\fP runned.
.TP 8
.B \-g, \--generate 
Generate proto and proto3 files from alphabet and sample text files.
.SH "SEE ALSO"
gxneur(1), kxneur(1)
.SH AUTHOR
Andrew Crew Kuznetsov, Nikolay Yankin
