.TH "gxneur" "1" 
.SH "NAME" 
gxneur \(em GTK frontend for xneur keyboard layout switcher 
.SH "SYNOPSIS" 
.PP 
\fBgxneur\fR 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly \fBgxneur\fR command. 
.PP 
gXNeur is a GTK frontend for xneur keyboard layout switcher. gXNeur runs in system tray and shows XNeur's state. It also allows to configure XNeur via GUI dialog. 
.SH "OPTIONS" 
.PP 
This program accepts no options. 
.SH "SEE ALSO" 
.PP 
xneur (1). 
.SH "AUTHOR" 
.PP 
This manual page was written by Alexander GQ Gerasiov <gq@cs.msu.su> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Thu 27 Dec 2007, 01:04 
