/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *label21;
  GtkWidget *image1;
  GtkWidget *hbuttonbox2;
  GtkWidget *button17;
  GtkWidget *hseparator1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("\320\236 gXNeur..."));
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  label21 = gtk_label_new (_("\n\t\t<b>X Neural Switcher for Gnome</b>\t\t\n\t\tGTK2 frontend for XNeur\t\t\n\nAUTHORS:\nAndrew Crew Kuznetsov\nNikolay Yankin"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (vbox1), label21, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_CENTER);

  image1 = create_pixmap (window1, "gxneur-run.png");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (vbox1), image1, TRUE, TRUE, 4);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_end (GTK_BOX (vbox1), hbuttonbox2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox2), 3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);

  button17 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (button17);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, TRUE, TRUE, 3);

  g_signal_connect_swapped ((gpointer) button17, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (window1));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (window1, button17, "button17");
  GLADE_HOOKUP_OBJECT (window1, hseparator1, "hseparator1");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GdkPixbuf *window2_icon_pixbuf;
  GtkWidget *vbox7;
  GtkWidget *notebook1;
  GtkWidget *vbox2;
  GtkWidget *hbox2;
  GtkWidget *label5;
  GtkWidget *combobox1;
  GtkWidget *hseparator2;
  GtkWidget *vbox5;
  GtkWidget *label16;
  GtkWidget *table1;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *combobox10;
  GtkWidget *combobox3;
  GtkWidget *combobox11;
  GtkWidget *combobox5;
  GtkWidget *combobox6;
  GtkWidget *combobox7;
  GtkWidget *combobox8;
  GtkWidget *combobox9;
  GtkWidget *hseparator5;
  GtkWidget *label25;
  GtkWidget *table3;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *label2;
  GtkWidget *table2;
  GtkWidget *label18;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *filechooserbutton1;
  GtkWidget *filechooserbutton2;
  GtkWidget *filechooserbutton3;
  GtkWidget *filechooserbutton4;
  GtkWidget *combobox13;
  GtkWidget *combobox14;
  GtkWidget *combobox15;
  GtkWidget *combobox16;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;
  GtkWidget *button6;
  GtkWidget *label3;
  GtkWidget *vbox8;
  GtkWidget *vbox3;
  GtkWidget *label6;
  GtkWidget *hbox3;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *vbox4;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *hseparator3;
  GtkWidget *vbox10;
  GtkWidget *label23;
  GtkWidget *hbox4;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeview2;
  GtkWidget *vbox11;
  GtkWidget *button19;
  GtkWidget *button20;
  GtkWidget *hseparator4;
  GtkWidget *vbox12;
  GtkWidget *label24;
  GtkWidget *hbox5;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview3;
  GtkWidget *vbox13;
  GtkWidget *button21;
  GtkWidget *button22;
  GtkWidget *label22;
  GtkWidget *hbuttonbox1;
  GtkWidget *button4;
  GtkWidget *button5;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("\320\235\320\260\321\201\321\202\321\200\320\276\320\271\320\272\320\260 XNeur"));
  gtk_window_set_resizable (GTK_WINDOW (window2), FALSE);
  window2_icon_pixbuf = create_pixbuf ("gxneur-run.png");
  if (window2_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window2), window2_icon_pixbuf);
      gdk_pixbuf_unref (window2_icon_pixbuf);
    }

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (window2), vbox7);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox7), notebook1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (notebook1), 3);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), vbox2,
                                      FALSE, FALSE, GTK_PACK_START);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 3);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, FALSE, TRUE, 0);

  label5 = gtk_label_new (_("<b>\320\240\320\265\320\266\320\270\320\274 \321\200\320\260\320\261\320\276\321\202\321\213 \320\277\321\200\320\276\320\263\321\200\320\260\320\274\320\274\321\213\t\t</b>"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_box_pack_start (GTK_BOX (hbox2), combobox1, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\320\220\320\262\321\202\320\276\320\274\320\260\321\202\320\270\321\207\320\265\321\201\320\272\320\270\320\271"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("\320\240\321\203\321\207\320\275\320\276\320\271"));

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator2, FALSE, TRUE, 4);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (vbox2), vbox5, FALSE, TRUE, 0);

  label16 = gtk_label_new (_("<b>\320\241\320\276\321\207\320\265\321\202\320\260\320\275\320\270\321\217 \320\272\320\273\320\260\320\262\320\270\321\210</b>"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (vbox5), label16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  table1 = gtk_table_new (4, 3, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox5), table1, FALSE, TRUE, 0);

  label12 = gtk_label_new (_("\320\227\320\260\320\274\320\265\320\275\320\260 \320\262\321\213\320\264\320\265\320\273\320\265\320\275\320\276\320\263\320\276 \321\202\320\265\320\272\321\201\321\202\320\260 "));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table1), label12, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  label13 = gtk_label_new (_("\320\241\320\274\320\265\320\275\320\260 \321\200\320\265\320\266\320\270\320\274\320\260 \321\200\320\260\320\261\320\276\321\202\321\213"));
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table1), label13, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  label14 = gtk_label_new (_("\320\227\320\260\320\274\320\265\320\275\320\260 \320\277\320\276\321\201\320\273\320\265\320\264\320\275\320\265\320\271 \321\201\321\202\321\200\320\276\320\272\320\270 "));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table1), label14, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("\320\227\320\260\320\274\320\265\320\275\320\260 / \320\236\321\202\320\274\320\265\320\275\320\260 \320\267\320\260\320\274\320\265\320\275\321\213 "));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table1), label15, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  combobox10 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox10);
  gtk_table_attach (GTK_TABLE (table1), combobox10, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("Shift"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("Ctrl"));

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_table_attach (GTK_TABLE (table1), combobox3, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("Break"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("ScrollLock"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("PrtSc"));

  combobox11 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox11);
  gtk_table_attach (GTK_TABLE (table1), combobox11, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox11), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox11), _("Shift"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox11), _("Ctrl"));

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_table_attach (GTK_TABLE (table1), combobox5, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Break"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("ScrollLock"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("PrtSc"));

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_table_attach (GTK_TABLE (table1), combobox6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Shift"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Ctrl"));

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_table_attach (GTK_TABLE (table1), combobox7, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Break"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("ScrollLock"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("PrtSc"));

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_table_attach (GTK_TABLE (table1), combobox8, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Shift"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Ctrl"));

  combobox9 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox9);
  gtk_table_attach (GTK_TABLE (table1), combobox9, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("Break"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("ScrollLock"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("PrtSc"));

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator5, FALSE, TRUE, 4);

  label25 = gtk_label_new (_("<b>\320\224\320\276\320\277\320\276\320\273\320\275\320\270\321\202\320\265\320\273\321\214\320\275\320\276</b>"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (vbox2), label25, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  table3 = gtk_table_new (2, 1, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox2), table3, FALSE, TRUE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("\320\236\320\261\321\200\320\260\320\261\320\260\321\202\321\213\320\262\320\260\321\202\321\214 \321\201\320\276\320\261\321\213\321\202\320\270\321\217 \320\274\321\213\321\210\320\270"));
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table3), checkbutton1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("\320\222\320\272\320\273\321\216\321\207\320\270\321\202\321\214 \321\200\320\265\320\266\320\270\320\274 \321\201\320\260\320\274\320\276\320\276\320\261\321\203\321\207\320\265\320\275\320\270\321\217"));
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table3), checkbutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label2 = gtk_label_new (_("\320\237\320\260\321\200\320\260\320\274\320\265\321\202\321\200\321\213"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label2);

  table2 = gtk_table_new (5, 4, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (notebook1), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 3);

  label18 = gtk_label_new (_("\320\235\320\260\320\267\320\262\320\260\320\275\320\270\320\265 \321\217\320\267\321\213\320\272\320\260"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table2), label18, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_table_attach (GTK_TABLE (table2), entry6, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 9679);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_table_attach (GTK_TABLE (table2), entry7, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 9679);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_table_attach (GTK_TABLE (table2), entry8, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 9679);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_table_attach (GTK_TABLE (table2), entry9, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 9679);

  label20 = gtk_label_new (_("\320\235\320\276\320\274\320\265\321\200\t"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table2), label20, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label19 = gtk_label_new (_("\320\237\320\260\320\277\320\272\320\260 \320\275\320\260\321\201\321\202\321\200\320\276\320\265\320\272"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table2), label19, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  filechooserbutton1 = gtk_file_chooser_button_new (_("\320\222\321\213\320\261\320\265\321\200\320\270\321\202\320\265 \321\204\320\260\320\271\320\273"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (filechooserbutton1);
  gtk_table_attach (GTK_TABLE (table2), filechooserbutton1, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  g_object_set (filechooserbutton1,
                "show-hidden", TRUE,
                NULL);

  filechooserbutton2 = gtk_file_chooser_button_new (_("\320\222\321\213\320\261\320\265\321\200\320\270\321\202\320\265 \321\204\320\260\320\271\320\273"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (filechooserbutton2);
  gtk_table_attach (GTK_TABLE (table2), filechooserbutton2, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  g_object_set (filechooserbutton2,
                "show-hidden", TRUE,
                NULL);

  filechooserbutton3 = gtk_file_chooser_button_new (_("\320\222\321\213\320\261\320\265\321\200\320\270\321\202\320\265 \321\204\320\260\320\271\320\273"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (filechooserbutton3);
  gtk_table_attach (GTK_TABLE (table2), filechooserbutton3, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  g_object_set (filechooserbutton3,
                "show-hidden", TRUE,
                NULL);

  filechooserbutton4 = gtk_file_chooser_button_new (_("\320\222\321\213\320\261\320\265\321\200\320\270\321\202\320\265 \321\204\320\260\320\271\320\273"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (filechooserbutton4);
  gtk_table_attach (GTK_TABLE (table2), filechooserbutton4, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  g_object_set (filechooserbutton4,
                "show-hidden", TRUE,
                NULL);

  combobox13 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox13);
  gtk_table_attach (GTK_TABLE (table2), combobox13, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("3"));

  combobox14 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox14);
  gtk_table_attach (GTK_TABLE (table2), combobox14, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox14), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox14), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox14), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox14), _("3"));

  combobox15 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox15);
  gtk_table_attach (GTK_TABLE (table2), combobox15, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox15), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox15), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox15), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox15), _("3"));

  combobox16 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox16);
  gtk_table_attach (GTK_TABLE (table2), combobox16, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox16), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox16), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox16), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox16), _("3"));

  button7 = gtk_button_new_with_mnemonic (_("\320\241\320\273\320\276\320\262\320\260\321\200\321\214..."));
  gtk_widget_show (button7);
  gtk_table_attach (GTK_TABLE (table2), button7, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button8 = gtk_button_new_with_mnemonic (_("\320\241\320\273\320\276\320\262\320\260\321\200\321\214..."));
  gtk_widget_show (button8);
  gtk_table_attach (GTK_TABLE (table2), button8, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button9 = gtk_button_new_with_mnemonic (_("\320\241\320\273\320\276\320\262\320\260\321\200\321\214..."));
  gtk_widget_show (button9);
  gtk_table_attach (GTK_TABLE (table2), button9, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button6 = gtk_button_new_with_mnemonic (_("\320\241\320\273\320\276\320\262\320\260\321\200\321\214..."));
  gtk_widget_show (button6);
  gtk_table_attach (GTK_TABLE (table2), button6, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label3 = gtk_label_new (_("\320\240\320\260\321\201\320\272\320\273\320\260\320\264\320\272\320\270"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label3);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox8);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox3, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("\320\241\320\277\320\270\321\201\320\276\320\272 \320\270\321\201\320\272\320\273\321\216\321\207\320\265\320\275\320\270\320\271"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox3), label6, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  hbox3 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (hbox3), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview1), FALSE);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox4, TRUE, TRUE, 0);

  button2 = gtk_button_new_with_mnemonic (_("\320\224\320\276\320\261\320\260\320\262\320\270\321\202\321\214..."));
  gtk_widget_show (button2);
  gtk_box_pack_start (GTK_BOX (vbox4), button2, FALSE, FALSE, 0);

  button3 = gtk_button_new_with_mnemonic (_("\320\243\320\264\320\260\320\273\320\270\321\202\321\214"));
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (vbox4), button3, FALSE, FALSE, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox8), hseparator3, TRUE, TRUE, 4);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox10, TRUE, TRUE, 0);

  label23 = gtk_label_new (_("\320\241\320\277\320\270\321\201\320\276\320\272 \320\264\320\273\321\217 \320\277\321\200\320\270\320\275\321\203\320\264\320\270\321\202\320\265\320\273\321\214\320\275\320\276\320\271 \320\260\320\262\321\202\320\276\320\274\320\260\321\202\320\270\321\207\320\265\321\201\320\272\320\276\320\271 \320\276\320\261\321\200\320\260\320\261\320\276\321\202\320\272\320\270"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (vbox10), label23, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  hbox4 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox4, TRUE, TRUE, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (hbox4), scrolledwindow4, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_SHADOW_IN);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeview2);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview2), FALSE);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox11, TRUE, TRUE, 0);

  button19 = gtk_button_new_with_mnemonic (_("\320\224\320\276\320\261\320\260\320\262\320\270\321\202\321\214..."));
  gtk_widget_show (button19);
  gtk_box_pack_start (GTK_BOX (vbox11), button19, FALSE, FALSE, 0);

  button20 = gtk_button_new_with_mnemonic (_("\320\243\320\264\320\260\320\273\320\270\321\202\321\214"));
  gtk_widget_show (button20);
  gtk_box_pack_start (GTK_BOX (vbox11), button20, FALSE, FALSE, 0);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox8), hseparator4, TRUE, TRUE, 4);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox12, TRUE, TRUE, 0);

  label24 = gtk_label_new (_("\320\241\320\277\320\270\321\201\320\276\320\272 \320\264\320\273\321\217 \320\277\321\200\320\270\320\275\321\203\320\264\320\270\321\202\320\265\320\273\321\214\320\275\320\276\320\271 \321\200\321\203\321\207\320\275\320\276\320\271 \320\276\320\261\321\200\320\260\320\261\320\276\321\202\320\272\320\270"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (vbox12), label24, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  hbox5 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox5, TRUE, TRUE, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (hbox5), scrolledwindow5, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_SHADOW_IN);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview3);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (treeview3), FALSE);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox13, TRUE, TRUE, 0);

  button21 = gtk_button_new_with_mnemonic (_("\320\224\320\276\320\261\320\260\320\262\320\270\321\202\321\214..."));
  gtk_widget_show (button21);
  gtk_box_pack_start (GTK_BOX (vbox13), button21, FALSE, FALSE, 0);

  button22 = gtk_button_new_with_mnemonic (_("\320\243\320\264\320\260\320\273\320\270\321\202\321\214"));
  gtk_widget_show (button22);
  gtk_box_pack_start (GTK_BOX (vbox13), button22, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("\320\237\321\200\320\270\320\273\320\276\320\266\320\265\320\275\320\270\321\217"));
  gtk_widget_show (label22);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label22);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox7), hbuttonbox1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  button4 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button4);
  gtk_container_set_border_width (GTK_CONTAINER (button4), 3);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  button5 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button5);
  gtk_container_set_border_width (GTK_CONTAINER (button5), 3);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) button4, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (window2));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (window2, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window2, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");
  GLADE_HOOKUP_OBJECT (window2, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window2, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window2, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (window2, label16, "label16");
  GLADE_HOOKUP_OBJECT (window2, table1, "table1");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, combobox10, "combobox10");
  GLADE_HOOKUP_OBJECT (window2, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (window2, combobox11, "combobox11");
  GLADE_HOOKUP_OBJECT (window2, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (window2, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (window2, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (window2, combobox8, "combobox8");
  GLADE_HOOKUP_OBJECT (window2, combobox9, "combobox9");
  GLADE_HOOKUP_OBJECT (window2, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (window2, label25, "label25");
  GLADE_HOOKUP_OBJECT (window2, table3, "table3");
  GLADE_HOOKUP_OBJECT (window2, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window2, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window2, label2, "label2");
  GLADE_HOOKUP_OBJECT (window2, table2, "table2");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window2, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window2, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window2, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, label19, "label19");
  GLADE_HOOKUP_OBJECT (window2, filechooserbutton1, "filechooserbutton1");
  GLADE_HOOKUP_OBJECT (window2, filechooserbutton2, "filechooserbutton2");
  GLADE_HOOKUP_OBJECT (window2, filechooserbutton3, "filechooserbutton3");
  GLADE_HOOKUP_OBJECT (window2, filechooserbutton4, "filechooserbutton4");
  GLADE_HOOKUP_OBJECT (window2, combobox13, "combobox13");
  GLADE_HOOKUP_OBJECT (window2, combobox14, "combobox14");
  GLADE_HOOKUP_OBJECT (window2, combobox15, "combobox15");
  GLADE_HOOKUP_OBJECT (window2, combobox16, "combobox16");
  GLADE_HOOKUP_OBJECT (window2, button7, "button7");
  GLADE_HOOKUP_OBJECT (window2, button8, "button8");
  GLADE_HOOKUP_OBJECT (window2, button9, "button9");
  GLADE_HOOKUP_OBJECT (window2, button6, "button6");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");
  GLADE_HOOKUP_OBJECT (window2, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (window2, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");
  GLADE_HOOKUP_OBJECT (window2, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window2, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window2, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (window2, button2, "button2");
  GLADE_HOOKUP_OBJECT (window2, button3, "button3");
  GLADE_HOOKUP_OBJECT (window2, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (window2, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (window2, label23, "label23");
  GLADE_HOOKUP_OBJECT (window2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (window2, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window2, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (window2, button19, "button19");
  GLADE_HOOKUP_OBJECT (window2, button20, "button20");
  GLADE_HOOKUP_OBJECT (window2, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (window2, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (window2, label24, "label24");
  GLADE_HOOKUP_OBJECT (window2, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (window2, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window2, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (window2, button21, "button21");
  GLADE_HOOKUP_OBJECT (window2, button22, "button22");
  GLADE_HOOKUP_OBJECT (window2, label22, "label22");
  GLADE_HOOKUP_OBJECT (window2, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window2, button4, "button4");
  GLADE_HOOKUP_OBJECT (window2, button5, "button5");

  return window2;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GdkPixbuf *dialog1_icon_pixbuf;
  GtkWidget *dialog_vbox1;
  GtkWidget *entry10;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview1;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog1), _("\320\240\320\265\320\264\320\260\320\272\321\202\320\270\321\200\320\276\320\262\320\260\320\275\320\270\320\265 \321\201\320\273\320\276\320\262\320\260\321\200\321\217"));
  gtk_window_set_resizable (GTK_WINDOW (dialog1), FALSE);
  dialog1_icon_pixbuf = create_pixbuf ("gxneur-run.png");
  if (dialog1_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog1), dialog1_icon_pixbuf);
      gdk_pixbuf_unref (dialog1_icon_pixbuf);
    }
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), entry10, FALSE, FALSE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entry10), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 9679);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), scrolledwindow3, TRUE, TRUE, 0);
  gtk_widget_set_size_request (scrolledwindow3, 384, 371);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview1);
  gtk_container_set_border_width (GTK_CONTAINER (textview1), 3);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) cancelbutton1, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (dialog1));
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (dialog1, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (dialog1, textview1, "textview1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton1, "okbutton1");

  return dialog1;
}

