#!/bin/sh

# Must be from GPG key
export DEBEMAIL="Andrew Crew Kuznetsov <andrewcrew@rambler.ru>"

if !([ -e xneur_*.orig.tar.gz ]); then
  echo "File xneur_*.orig.tar.gz is not found.";
  export OLD_VER=0;
else
  export OLD_VER=$(ls xneur_*.orig.tar.gz | sed -e "s/^xneur_\(.*\).orig.tar.gz$/\1/");
fi

export LAST_REVISION=$(git rev-list HEAD --count)

echo "Number of last revision: ${LAST_REVISION}"

if [ -z ${LAST_REVISION} ]; then
  echo "Error: number of last revision is empty!";
  exit 0;
fi

echo "Updating is started."
# begin local updating
git pull

export CUR_VER=$(cat ../xneur/configure.ac | grep "AC_INIT" | sed -e "s/^AC_INIT(xneur, \(.*\))$/\1/")
export NEW_VER="${CUR_VER}"

echo "OLD_VER = ${OLD_VER}"
echo "NEW_VER = ${NEW_VER}"

if [ ${NEW_VER} = ${OLD_VER} ]; then
	echo "Upgrading is not required.";
	read -p "You'r rebuild packages (y/N)?" RESP
	
	if [ "$RESP" != y ] ; then
		echo "Rebuilding is not required.";
		exit 0;
	fi
fi

# begin local updating
cp -rf ../xneur/ ./xneur-tmp

# building to dist
cd ./"xneur-tmp"
# save debianize settings
mv ./debian ../
./autogen.sh
make dist
mkdir ../"xneur-${CUR_VER}"
tar -xvf "xneur-${CUR_VER}.tar.gz" -C ../
cd ..
rm -R ./"xneur-tmp"
# end building

#Create .orig.tar.gz
tar -czf "xneur_$NEW_VER.orig.tar.gz" "xneur-${CUR_VER}"

cd "xneur-${CUR_VER}"
# restore debianize settings
mv ../debian ./

read -p "Build package only on local system (y/N)?" RESPONSE
echo
if [ "$RESPONSE" = y ] ; then
        
	# If you want to build package on your system uncomment this:
	dch -v "$NEW_VER-mybuild1" "Minor update."
	dpkg-buildpackage -rfakeroot

	cd ..
	rm -R ./"xneur-${NEW_VER}"
	rm -R ./"xneur-${CUR_VER}"
else

# Note: I am using gnupg-agent for comfortable work

# begin update for basic releases 
dch -b --force-distribution --distribution "cosmic" -v "${NEW_VER}-0cosmic" \
  "Minor update."
debuild -S -sa
# end update for basic releases

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "bionic" -v "${NEW_VER}-0bionic" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "artful" -v "${NEW_VER}-0artful" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "xenial" -v "${NEW_VER}-0xenial" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "trusty" -v "${NEW_VER}-0trusty" \
  "Automated backport upload; no source changes."
debuild -S -sd

cp -f ../changelog debian/changelog
dch -b --force-distribution --distribution "precise" -v "${NEW_VER}-0precise" \
  "Automated backport upload; no source changes."
debuild -S -sd


# end update for other releases

cd ..
echo "Download to Launchpad Cosmic..."
dput ppa xneur_${NEW_VER}-0cosmic_source.changes | cat
echo "Download to Launchpad Bionic..."
dput ppa xneur_${NEW_VER}-0bionic_source.changes | cat
echo "Download to Launchpad Artful..."
dput ppa xneur_${NEW_VER}-0artful_source.changes | cat
echo "Download to Launchpad Xenial..."
dput ppa xneur_${NEW_VER}-0xenial_source.changes | cat
echo "Download to Launchpad Trusty..."
dput ppa xneur_${NEW_VER}-0trusty_source.changes | cat
echo "Download to Launchpad Precise..."
dput ppa xneur_${NEW_VER}-0precise_source.changes | cat

rm -R ./"xneur-${NEW_VER}"
rm -R ./"xneur-${CUR_VER}"
fi

echo "Update xneur finished successfully"


